import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Common/Header";
import LeftBar from "./(withLeftBar)/LeftBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
  icons: "../public/next.svg"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="flex items-start">
          <LeftBar />
          <div className="flex flex-col flex-1">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
